drop table if exists sosocal_task;
create table sosocal_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

drop table if exists sosocal_user;
create table sosocal_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);


DROP TABLE IF EXISTS `sosocal_event`;
CREATE TABLE `sosocal_event` (
  `id` bigint generated by default as identity,
  `user_id` INT NOT NULL,
  `project_id` int NOT NULL,
  `priority` int NOT NULL,
  `comment_floor` int NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `detail` varchar(255) NULL,
  PRIMARY KEY (`id`)
);


DROP TABLE IF EXISTS `sosocal_team_user`;
CREATE TABLE `sosocal_team_user` (
  `id` bigint generated by default as identity,
  `user_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`user_id`, `team_id`)
);

DROP TABLE IF EXISTS `sosocal_comment`;
CREATE TABLE `sosocal_comment` (
  `id` bigint generated by default as identity,
  `user_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `floor` int NOT NULL,
  `score` int NOT NULL,
  `detail` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
);


DROP TABLE IF EXISTS `sosocal_team`;
CREATE TABLE `sosocal_team` (
  `id` bigint generated by default as identity,
  `name` VARCHAR(32) NOT NULL,
  `description` varchar(255) NULL,
  `active` int NOT NULL DEFAULT 1,
  `create_day` DATE NOT NULL,
  PRIMARY KEY (`id`)
);


DROP TABLE IF EXISTS `sosocal_project`;
CREATE TABLE `sosocal_project` (
  `id` bigint generated by default as identity,
  `name` VARCHAR(32) NOT NULL,
  `description` varchar(255) NULL,
  `active` int NOT NULL,
  `create_day` DATE NOT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `sosocal_review`;
CREATE TABLE `sosocal_review` (
  `id` bigint generated by default as identity,
  `user_id` INT NOT NULL,
  `score` int NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  `start_day` DATE NOT NULL,
  `end_day` DATE NULL,
  `detail` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
);
